    {"Alright, I think I've rescued enough slaves to stir up some trouble for WEAPCO!", "Отлично, похоже, я спас достаточно рабов, чтобы устроить WEAPCO серьёзные проблемы!"},
    {"HULL BREACHED! SYSTEMS FAILING! F-...", "КОРПУС ПРОБИТ! СИСТЕМЫ ОТКАЗЫВАЮТ! БЛ-..."},
    {"That's one less surprise that WEAPCO can spring on us!", "Одним сюрпризом WEAPCO для нас стало меньше!"},
    {"Time Remaining - %.2d:%.2d", "Осталось времени — %.2d:%.2d"},
