    {"We took down the WEAPCO mining vessel and then I was jumped by a man claiming to be Kline Kethlan.", "Мы справились с добывающим кораблём WEAPCO, а затем меня перехватил человек, назвавшийся Клайном Кетланом."},
    {"He did put up one hell of a fight! He didn't stick around for long, though.", "Сопротивлялся он серьёзно! Правда, надолго не задержался."},
    {"We should probably destroy that craft, then. We might be able to thwart its development somewhat.", "Тогда стоит вывести этот корабль из строя. Возможно, это заметно затормозит разработку."},
