    {"What have you found out about that experimental fighter?", "Что удалось узнать об этом экспериментальном истребителе?"},
    {"It's got some kind of cloaking device that makes it invisible to radar. Could prove hard to track down.", "На нём установлено маскировочное устройство, из-за которого он невидим для радара. Найти его будет непросто."},
    {"I'll just have to run around the system until I find it.", "Значит, придётся прочесать всю систему, пока я его не найду."},
    {"It's likely to run away if you engage it in battle, so try and do as much damage to it as possible.", "Если вступишь с ним в бой, он наверняка попытается уйти. Постарайся нанести ему как можно больше урона."},
