    {"While you were gone I picked up a distress call coming from around Jupiter.", "Пока тебя не было, я поймал сигнал бедствия из района Юпитера."},
    {"Who would be sending out a distress call within Sol?", "Кто вообще может подавать сигнал бедствия внутри Солнечной системы?"},
    {"Let's check it out. Even if it's a trap, I think we can handle it.", "Давайте проверим. Даже если это ловушка, думаю, мы справимся."},
