    {"WEAPCO has set up a highly dangerous defense line between Saturn and Uranus. We'll need to take it out.", "WEAPCO развернула крайне опасную линию обороны между Сатурном и Ураном. Нам придётся её устранить."},
    {"What kind of defense system?", "Что это за система обороны?"},
    {"Several mobile Energy Ray cannons, not unlike the weapon used by the Star Killer back in Spirit.", "Несколько мобильных энергетических пушек, похожих на оружие «Убийцы звёзд» в системе Spirit."},
    {"Best check my ejection system, then!", "Тогда лучше проверить систему катапультирования!"},
