    {"Seems like taking out that WEAPCO mining ship wasn't such a good idea. The ore it collected is needed in weapons production.", "Похоже, идея вывести из строя добывающий корабль WEAPCO была не лучшей. Собранная им руда нужна для производства оборудования."},
    {"Damn! I guess that means I'll have to mine some myself, then, huh?", "Вот чёрт! Значит, теперь мне придётся добыть руду самому?"},
    {"Yes. Be careful, Chris. Your weapons weren't designed for that sort of work, after all.", "Да. Будь осторожен, Крис. Твоё оборудование всё-таки не предназначено для такой работы."},
